-- MySQL Script generated by MySQL Workbench
-- Sun Apr  9 22:36:29 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
-- ---
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema biblioteca_mvc
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema biblioteca_mvc
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `biblioteca_mvc` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `biblioteca_mvc` ;

-- -----------------------------------------------------
-- Table `biblioteca_mvc`.`autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca_mvc`.`autor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `autor` VARCHAR(150) NOT NULL,
  `imagen` VARCHAR(100) NOT NULL,
  `estado` INT NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `biblioteca_mvc`.`configuracion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca_mvc`.`configuracion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(200) NOT NULL,
  `telefono` VARCHAR(20) NOT NULL,
  `direccion` TEXT NOT NULL,
  `correo` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `biblioteca_mvc`.`editorial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca_mvc`.`editorial` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `editorial` VARCHAR(150) NOT NULL,
  `estado` INT NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `biblioteca_mvc`.`libro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca_mvc`.`libro` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` TEXT NOT NULL,
  `cantidad` INT NOT NULL,
  `id_autor` INT NOT NULL,
  `id_editorial` INT NOT NULL,
  `anio_edicion` DATE NOT NULL,
  `id_materia` INT NOT NULL,
  `num_pagina` INT NOT NULL,
  `descripcion` TEXT NOT NULL,
  `imagen` VARCHAR(100) NOT NULL,
  `estado` INT NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `biblioteca_mvc`.`materia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca_mvc`.`materia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `materia` TEXT NOT NULL,
  `estado` INT NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `biblioteca_mvc`.`membresia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca_mvc`.`membresia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(200) NOT NULL,
  `precio` INT NULL DEFAULT NULL,
  `tipo` VARCHAR(200) NOT NULL,
  `estado` INT NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `biblioteca_mvc`.`prestamo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca_mvc`.`prestamo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `id_libro` INT NOT NULL,
  `fecha_prestamo` DATE NOT NULL,
  `fecha_devolucion` DATE NOT NULL,
  `cantidad` INT NOT NULL,
  `observacion` TEXT NOT NULL,
  `estado` INT NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 41
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `biblioteca_mvc`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca_mvc`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `correo` VARCHAR(80) NULL DEFAULT NULL,
  `usuario` VARCHAR(50) NOT NULL,
  `nombre` VARCHAR(200) NOT NULL,
  `clave` VARCHAR(100) NOT NULL,
  `rol` VARCHAR(20) NOT NULL,
  `estado` INT NOT NULL DEFAULT '1',
  `membresiaEstado` VARCHAR(20) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `useremail_UNIQUE` (`correo` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 46
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
